FROM carlosperez/mesos-tensorflow-gpu

# Based on container from Craig Citro <craigcitro@google.com>
MAINTAINER Carlos Perez <carlos.perez@epfl.ch>

# Set up our notebook config.
COPY jupyter_notebook_config.py /root/.jupyter/

# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
COPY /run_jupyter.sh /

# Copy sample notebooks.
COPY notebooks /notebooks

WORKDIR "/notebooks"

CMD ["/run_jupyter.sh"]